---
name: automerge
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.actor }}
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'glazychev-art' }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Only allow go.mod, go.sum, *.gen.go files
        run: |
          git rev-parse HEAD
          find . -type f ! -name '*.yaml' ! -name '*.yml' -exec git diff --exit-code HEAD^ -- {} +
      - name: Merge PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: glazychev-art
          ENABLED_FOR_MANUAL_CHANGES: true
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          MAXIMUM_RETRIES: 25
