---
name: Update references
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  update-refs:
    name: Update references
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch main
        run: |
          git remote -v
          git fetch --depth=1 origin main
      - name: Update references
        run: |
          sed -r -i 's/(ref=.*)/ref="${{ github.sha }}"/g' `grep 'ref=' -rl *`
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git add -- .
          git commit -s -m "Update references"
